### ISSUE TITLE
problems with dynamic library + dynamic binding

### ISSUE THREAD

**Issue by svdztn** [namhyung/uftrace#368] opened 2018-05-25 02:32 UTC
Hello,
I came across 2 problems with dynamic library.

No1.
According to #283, I use the second example(using `dlopen`).There is something wrong using subcommand  `graph`.

```
$ uftrace record ./dl-calc
$ uftrace replay          
# DURATION     TID     FUNCTION
            [  3000] | main() {
 463.863 us [  3000] |   dlopen();
   5.684 us [  3000] |   dlsym();
   0.664 us [  3000] |   add();
  27.769 us [  3000] |   dlclose();
 516.549 us [  3000] | } /* main */
```
```
$ uftrace graph 
# Function Call Graph for 'dl-calc' (session: f1516ec8b194f644)
========== FUNCTION CALL GRAPH ==========
# TOTAL TIME   FUNCTION
  516.549 us : (1) dl-calc
  516.549 us : (1) main
  463.863 us :  +-(1) dlopen
             :  | 
    5.684 us :  +-(1) dlsym
             :  | 
    0.664 us :  +-(1) <b76ea411>
             :  | 
   27.769 us :  +-(1) dlclose
```
The symbol of “add()” is missing.

No2.
In our project(using c++), there are many generations of derived classes. And we put them in dynamic libraries.
This is an example:
```
$ cat grandfather.h
#include <stdio.h>

class CGrandfather
{
public:
    virtual void func();
};

$ cat grandfather.cpp
#include "grandfather.h"

void CGrandfather::func()
{
	printf("Grandfather\n");
}

g++ -pg -fPIC -c grandfather.cpp -I./
g++ -pg -shared -o libgrandfather.so grandfather.o
```
```
$ cat father.h  
#include <stdio.h>
#include "grandfather.h"

class CFather : public CGrandfather
{
public:
    virtual void func();
    virtual void func2();
};

$ cat father.cpp
#include "father.h"

void CFather::func()
{
	func2();
}
void CFather::func2()
{
	printf("Father\n");
}

g++ -pg -fPIC -c father.cpp -I./
g++ -pg -shared -o libfather.so father.o -L./ -lgrandfather
```
```
$ cat child.cpp 
#include "father.h"

class CChild : public CFather
{
public:
	void func2()
	{
		printf("Child\n");
	};
};

extern "C" CGrandfather* creat()
{
	return new CChild;
}

g++ -pg -fPIC -c child.cpp -I./
g++ -pg -shared -o libchild.so child.o -L./ -lfather -lgrandfather
```
```
$ cat main.cpp  
#include "dlfcn.h"
#include "grandfather.h"

int main()
{
	CGrandfather* prt;
        void *handle = dlopen("libchild.so", RTLD_LAZY);
        CGrandfather* (*dl_creat)() = (CGrandfather* (*)())dlsym(handle, "creat");
        prt = dl_creat();
	prt -> func();
	dlclose(handle);
}

g++ -pg -o main main.cpp -I./ -L./  -ldl -lgrandfather

export LD_LIBRARY_PATH=./
```

Result:
```
$ uftrace ./main
Child
# DURATION     TID     FUNCTION
            [  2931] | main() {
 129.739 us [  2931] |   dlopen();
   1.178 us [  2931] |   dlsym();
            [  2931] |   creat() {
            [  2931] |     CChild::CChild() {
            [  2931] |       CFather::CFather() {
   0.263 us [  2931] |         CGrandfather::CGrandfather();
   1.288 us [  2931] |       } /* CFather::CFather */
   2.202 us [  2931] |     } /* CChild::CChild */
   5.824 us [  2931] |   } /* creat */
            [  2931] |   <b76d1684>() {
   3.787 us [  2931] |     CChild::func2();
   4.436 us [  2931] |   } /* <b76d1684> */
   9.372 us [  2931] |   dlclose();
 157.342 us [  2931] | } /* main */
```

`prt `points to `CChild`,so `prt->fun()` should be `CChild::func()`.
`CChild` did not override `func()`,so it is `CFather::func()`

In file uftrace.data/libchild.so.sym, there is no function `func()`.
And in file libchild.so,the symbol is `CFather::func()`.
```
$ cat uftrace.data/libchild.so.sym |grep func
00000000000008ea w _ZN6CChild5func2Ev
```
```
$ readelf -Ws libchild.so |grep func
     3: 00000000     0 FUNC    GLOBAL DEFAULT  UND _ZN7CFather4funcEv
    23: 000008ea    44 FUNC    WEAK   DEFAULT   11 _ZN6CChild5func2Ev
    53: 00000000     0 FUNC    GLOBAL DEFAULT  UND _ZN7CFather4funcEv
    55: 000008ea    44 FUNC    WEAK   DEFAULT   11 _ZN6CChild5func2Ev
```

Thanks for reading.
uftrace is quite a good tool, look forward to solve this.

**Comment by namhyung** [comment] 2018-05-25 06:14
Thanks for using uftrace and reporting the problem.  I can reproduce it on my system, will take a look.

**Comment by namhyung** [comment] 2018-05-25 07:38
It didn't handle the case of loading multiple libraries in a single `dlopen()`.  I pushed the fix to [check/dlopen-fix](https://github.com/namhyung/uftrace/compare/check/dlopen-fix).  Could you please confirm that it fixes your problem?

**Comment by svdztn** [comment] 2018-05-25 09:40
@namhyung 
It works well now, excelent !
Thanks for the quick answer and fix.

p.s.
I am not sure about the failure in the debug message.
```
$ uftrace -v ./main
uftrace: skipping perf event due to error: Invalid argument
uftrace: creating 1 thread(s) for recording
uftrace: using libmcount.so library for tracing
mcount: initializing mcount library
mcount: setup PLT hooking 
mcount: mcount setup done
mcount: new session started: 6a2e03cd811b4c14: main
mcount: shmem_finish: tid: 4926 seqnum = 0 curr = 0, nr_buf = 2 max_buf = 2
mcount: exit from libmcount
153639656
Child
uftrace: child terminated with exit code: 0
uftrace: cannot find build-id section
uftrace: reading /tmp/uftrace-live-V9j5dM/task.txt file
uftrace: flushing /uftrace-6a2e03cd811b4c14-4926-000
uftrace: live-record finished.. 
uftrace: start live-replaying...
uftrace: reading /tmp/uftrace-live-V9j5dM/task.txt file
uftrace: failed to search perf data file
fstack: fixup for some special functions
uftrace: add field "duration"
uftrace: add field "tid"
# DURATION     TID     FUNCTION
            [  4926] | main() {
 268.111 us [  4926] |   dlopen();
   3.265 us [  4926] |   dlsym();
            [  4926] |   creat() {
            [  4926] |     CChild::CChild() {
            [  4926] |       CFather::CFather() {
   0.943 us [  4926] |         CGrandfather::CGrandfather();
   2.547 us [  4926] |       } /* CFather::CFather */
   3.826 us [  4926] |     } /* CChild::CChild */
  11.123 us [  4926] |   } /* creat */
   7.779 us [  4926] |   printf();
            [  4926] |   CFather::func() {
   1.507 us [  4926] |     CChild::func2();
   2.498 us [  4926] |   } /* CFather::func */
  13.622 us [  4926] |   dlclose();
 320.103 us [  4926] | } /* main */
uftrace: removing /tmp/uftrace-live-V9j5dM directory
```

**Comment by namhyung** [comment] 2018-05-25 11:48
Cool! thanks for testing.

The failure is from the perf_event setting which requires recent kernel and libc.  But that's ok to ignore since it's just for some extra information.

**Closed** 2018-05-25 12:34 UTC

**Comment by svdztn** [comment] 2018-05-26 00:11
@namhyung
btw, is the "printf();" at the wrong place?

**Comment by namhyung** [comment] 2018-05-26 13:00
Hmm.. right.  Actually it cannot trace `printf()` in the child class since PLT hooking is not enabled for dlopen libraries.  It looks like called from the main executable and I'm also curious about the output having "153639656" in your result.

**Comment by svdztn** [comment] 2018-05-28 00:57
@namhyung 
Uhh... It's my problem. 
I forgot that I added a `print()` in `main()` to test something else.
Sorry for that.

Thanks for reply.

**Comment by namhyung** [comment] 2018-05-28 02:18
That's ok, glad to hear that no problem any more :)
