### ISSUE TITLE
t161_pltbind_now.py runtest error ?

### ISSUE THREAD

**Issue by ssove** [namhyung/uftrace#136] opened 2017-08-24 06:17 UTC
Hi.

I tried `./runtest.py ` to test uftrace, but it stopped when trying to test `t161_pltbind_now.py`.
<br>So I tried again with `gcc -o t-openclose -fno-inline -fno-builtin -fno-omit-frame-pointer  -pg -O0  s-openclose.c   -Wl,-z,now -Wl,-z,relro`, but it did nothing.
<br>Could you inform me what I did wrong ?

**Comment by JW1031** [comment] 2017-08-24 08:00
In my system environment, I can't find that problem. :(
```
# system information
# ==================
# program version     : uftrace v0.7-198-g038d
# recorded on         : Thu Aug 24 16:36:31 2017
# cmdline             : uftrace record a.out 
# cpu info            : Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
# number of cpus      : 2 / 2 (online / possible)
# memory info         : 0.5 / 1.9 GB (free / total)
# system load         : 0.06 / 0.07 / 0.01 (1 / 5 / 15 min)
# kernel version      : Linux 4.10.0-19-generic
# hostname            : jeongwoo-VirtualBox
# distro              : "Ubuntu 17.04"
#

```

**Comment by ssove** [comment] 2017-08-24 08:25
Following is my system environment. 
# system information
# ==================
# program version     : uftrace v0.7-198-g038d
# recorded on         : Thu Aug 24 17:21:26 2017
# cmdline             : uftrace record a.out 
# cpu info            : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
# number of cpus      : 1 / 1 (online / possible)
# memory info         : 0.6 / 1.9 GB (free / total)
# system load         : 0.06 / 0.02 / 0.00 (1 / 5 / 15 min)
# kernel version      : Linux 4.10.0-28-generic
# hostname            : ubuntu
# distro              : "Ubuntu 16.04.3 LTS"
#
I cannot see the problem in system settings..

**Comment by ssove** [comment] 2017-08-24 08:31
Following is my system environment.

- system information
-  ==================
- program version     : uftrace v0.7-198-g038d
-  recorded on         : Thu Aug 24 17:21:26 2017
-  cmdline             : uftrace record a.out 
-  cpu info            : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
-  number of cpus      : 1 / 1 (online / possible)
-  memory info         : 0.6 / 1.9 GB (free / total)
-  system load         : 0.06 / 0.02 / 0.00 (1 / 5 / 15 min)
-  kernel version      : Linux 4.10.0-28-generic
-  hostname            : ubuntu
-  distro              : "Ubuntu 16.04.3 LTS"

I can't see the problem in system settings..

**Comment by namhyung** [comment] 2017-08-24 14:24
Nothing seems to be wrong in your setting.  Could you please run uftrace with -v option to show debug messages?

**Comment by honggyukim** [comment] 2017-08-25 01:49
@namhyung I've seen it a bit, the thing is that `-Wl,-z,now -Wl,-z,relro` doesn't change the plt structure but `-pie` changes it. It seems that having only bind-now resolves got tables at startup time without changing plt structure. You can reproduce it by running `t161_pltbind_now.py` using gcc older than 6.0, the so please check it again.

**Comment by honggyukim** [comment] 2017-08-25 02:09
I've compared two `t-openclose` binaries between `gcc-4.8.4` and `gcc-6.3.0`. Here is the difference in `readelf` output.
- `t-openclose-4.8.4` by `gcc-4.8.4` with `-finstrument-functions`
```
$ readelf -d t-openclose-4.8.4
  ...
Dynamic section at offset 0xdc0 contains 26 entries:
  Tag        Type                         Name/Value
    ...
 0x0000000000000018 (BIND_NOW)
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
    ...
```
```
$ uftrace t-openclose-4.8.4
# DURATION    TID     FUNCTION
            [16695] | main() {
   6.366 us [16695] |   <400530>();
  11.570 us [16695] | } /* main */
```

- `t-openclose-6.3.0` by `gcc-6.3.0` with `-finstrument-functions`
```
$ readelf -d t-openclose-6.3.0
  ...
Dynamic section at offset 0xdd8 contains 24 entries:
  Tag        Type                         Name/Value
    ...
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW PIE
    ...
```
```
$ uftrace t-openclose-6.3.0
# DURATION    TID     FUNCTION
            [17501] | main() {
   3.448 us [17501] |   open();
   1.113 us [17501] |   close();
   6.368 us [17501] | } /* main */
```

**Comment by honggyukim** [comment] 2017-08-25 02:13
In the `t-openclose-4.8.4` example, strange address `<400530>` is catched, you will find that no function is detected if you compile it with `-pg`. It seems to be a gcc bug.
```
$ objdump -d t-openclose-4.8.4
   ...
  1 0000000000400550 ma<main>:
  2   400550:       55                      push   %rbp
  3     ...
  4   40055f:       e8 dc ff ff ff          callq  400540 <__cyg_profile_func_enter@plt>
  5     ...
  6   40056d:       e8 ce ff ff ff          callq  400540 <__cyg_profile_func_enter@plt>
  7     ...
  8   40057b:       e8 b0 ff ff ff          callq  400530 <open@plt>
  9     ...
 10   40058b:       e8 90 ff ff ff          callq  400520 <__cyg_profile_func_exit@plt>
 11     ...
 12   400592:       e8 59 ff ff ff          callq  4004f0 <close@plt>
 13     ...
 14   4005a0:       e8 7b ff ff ff          callq  400520 <__cyg_profile_func_exit@plt>
 15     ...
 16   4005aa:       c3                      retq
  ...
```
In the above output, line number 4 and 14 are function entry and exit for `main`, and line number 6 and 10 are function entry and exit for `open@plt`. Howevier, gcc must not create the hooking functions for library calls. In this case, it only inserts hooking functions for `open@plt` but not for `close@plt`. It looks like a gcc bug as far as I understand.

**Comment by honggyukim** [comment] 2017-08-25 02:18
We have to study more on bind now check but I think the below change can fix the problem as of now, but it has a compilation error because `PF_1_PIE` is not defined but shown in `readelf`.
```
diff --git a/utils/symbol.c b/utils/symbol.c
index d396b80..a29ec52 100644
--- a/utils/symbol.c
+++ b/utils/symbol.c
@@ -565,7 +565,8 @@ static int load_dynsymtab(struct symtab *dsymtab, const char *filename,
                        plt_found = true;
                else if (dyn.d_tag == DT_BIND_NOW)
                        bind_now = true;
-               else if (dyn.d_tag == DT_FLAGS_1 && (dyn.d_un.d_val & DF_1_NOW))
+               else if (dyn.d_tag == DT_FLAGS_1 && (dyn.d_un.d_val & DF_1_NOW)
+                                                && (dyn.d_un.d_val & DF_1_PIE))
                        bind_now = true;
        }
```
@namhyung Please take a look at it.

**Comment by honggyukim** [comment] 2017-08-25 02:37
This can be a separate issue but in the `t-openclose-4.8.4` example, strange address `<400530>` is catched, you will find that no function is detected if you compile it with `-pg`.
```
$ gcc -Wl,-z,now -Wl,-z,relro s-openclose.c -O2 -pg
$ uftrace ./a.out
# DURATION    TID     FUNCTION
   9.980 us [21650] | main();

$ gcc -Wl,-z,now -Wl,-z,relro s-openclose.c -O2 -finstrument-functions
$ uftrace ./a.out
# DURATION    TID     FUNCTION
            [21590] | main() {
   6.446 us [21590] |   <400530>();
  11.473 us [21590] | } /* main */

$ gcc s-openclose.c -O2 -finstrument-functions
$ uftrace ./a.out
# DURATION    TID     FUNCTION
            [21872] | main() {
            [21872] |   open() {
   7.947 us [21872] |     open();
  13.393 us [21872] |   } /* open */
   3.893 us [21872] |   close();
  18.954 us [21872] | } /* main */

$ gcc s-openclose.c -O2 -pg
$ uftrace ./a.out
# DURATION    TID     FUNCTION
   1.506 us [21994] | __monstartup();
   0.887 us [21994] | __cxa_atexit();
            [21994] | main() {
   8.177 us [21994] |   open();
   3.997 us [21994] |   close();
  13.897 us [21994] | } /* main */
```
It seems to be a gcc bug in `-finstrument-functions`.
```
$ objdump -d t-openclose-4.8.4
   ...
  1 0000000000400550 <main>:
  2   400550:       55                      push   %rbp
  3     ...
  4   40055f:       e8 dc ff ff ff          callq  400540 <__cyg_profile_func_enter@plt>
  5     ...
  6   40056d:       e8 ce ff ff ff          callq  400540 <__cyg_profile_func_enter@plt>
  7     ...
  8   40057b:       e8 b0 ff ff ff          callq  400530 <open@plt>
  9     ...
 10   40058b:       e8 90 ff ff ff          callq  400520 <__cyg_profile_func_exit@plt>
 11     ...
 12   400592:       e8 59 ff ff ff          callq  4004f0 <close@plt>
 13     ...
 14   4005a0:       e8 7b ff ff ff          callq  400520 <__cyg_profile_func_exit@plt>
 15     ...
 16   4005aa:       c3                      retq
  ...
```
In the above output, line number 4 and 14 are function entry and exit for `main`, and line number 6 and 10 are function entry and exit for `open@plt`. Howevier, gcc must not create the hooking functions for library calls. In this case, it only inserts hooking functions for `open@plt` but not for `close@plt`. It looks like a gcc bug as far as I understand.

**Comment by honggyukim** [comment] 2017-08-25 02:39
I've tested it again with `gcc-6.3.0`, and it seems that the problem is disappeared.
```
$ gcc s-openclose.c -O2 -no-pie -finstrument-functions
$ uftrace ./a.out
# DURATION    TID     FUNCTION
            [18259] | main() {
   3.420 us [18259] |   open();
   1.069 us [18259] |   close();
   6.895 us [18259] | } /* main */
```
Here is the objdump output.
```
0000000000400500 <main>:
  400500:   48 83 ec 08             sub    $0x8,%rsp
    ...
  400510:   e8 db ff ff ff          callq  4004f0 <__cyg_profile_func_enter@plt>
    ...
  400520:   e8 bb ff ff ff          callq  4004e0 <open@plt>
    ...
  400527:   e8 94 ff ff ff          callq  4004c0 <close@plt>
    ...
  400538:   e8 93 ff ff ff          callq  4004d0 <__cyg_profile_func_exit@plt>
    ...
  400543:   c3                      retq
    ...
```

**Comment by namhyung** [comment] 2017-08-25 04:29
@honggyukim Thanks for the detailed report.  Could you please show me the disassembly of .plt and .plt.got of t-openclose-4.8.4?  I thought only BIND_NOW could change PLT structure since it doesn't need to fallback to PLT0.

**Comment by honggyukim** [comment] 2017-08-25 06:20
Here is the objdump output that you requested:
```
$ objdump -d t-openclose-4.8.4
  ...
Disassembly of section .plt:

00000000004004e0 <close@plt-0x10>:
  4004e0:       ff 35 d2 0a 20 00       pushq  0x200ad2(%rip)        # 600fb8 <_GLOBAL_OFFSET_TABLE_+0x8>
  4004e6:       ff 25 d4 0a 20 00       jmpq   *0x200ad4(%rip)        # 600fc0 <_GLOBAL_OFFSET_TABLE_+0x10>
  4004ec:       0f 1f 40 00             nopl   0x0(%rax)

00000000004004f0 <close@plt>:
  4004f0:       ff 25 d2 0a 20 00       jmpq   *0x200ad2(%rip)        # 600fc8 <_GLOBAL_OFFSET_TABLE_+0x18>
  4004f6:       68 00 00 00 00          pushq  $0x0
  4004fb:       e9 e0 ff ff ff          jmpq   4004e0 <_init+0x28>

0000000000400500 <__libc_start_main@plt>:
  400500:       ff 25 ca 0a 20 00       jmpq   *0x200aca(%rip)        # 600fd0 <_GLOBAL_OFFSET_TABLE_+0x20>
  400506:       68 01 00 00 00          pushq  $0x1
  40050b:       e9 d0 ff ff ff          jmpq   4004e0 <_init+0x28>

0000000000400510 <__gmon_start__@plt>:
  400510:       ff 25 c2 0a 20 00       jmpq   *0x200ac2(%rip)        # 600fd8 <_GLOBAL_OFFSET_TABLE_+0x28>
  400516:       68 02 00 00 00          pushq  $0x2
  40051b:       e9 c0 ff ff ff          jmpq   4004e0 <_init+0x28>

0000000000400520 <__cyg_profile_func_exit@plt>:
  400520:       ff 25 ba 0a 20 00       jmpq   *0x200aba(%rip)        # 600fe0 <_GLOBAL_OFFSET_TABLE_+0x30>
  400526:       68 03 00 00 00          pushq  $0x3
  40052b:       e9 b0 ff ff ff          jmpq   4004e0 <_init+0x28>

0000000000400530 <open@plt>:
  400530:       ff 25 b2 0a 20 00       jmpq   *0x200ab2(%rip)        # 600fe8 <_GLOBAL_OFFSET_TABLE_+0x38>
  400536:       68 04 00 00 00          pushq  $0x4
  40053b:       e9 a0 ff ff ff          jmpq   4004e0 <_init+0x28>

0000000000400540 <__cyg_profile_func_enter@plt>:
  400540:       ff 25 aa 0a 20 00       jmpq   *0x200aaa(%rip)        # 600ff0 <_GLOBAL_OFFSET_TABLE_+0x40>
  400546:       68 05 00 00 00          pushq  $0x5
  40054b:       e9 90 ff ff ff          jmpq   4004e0 <_init+0x28>
  ...
```
There's no `.got.plt` section in t-openclose-4.8.4, it only has `.got` section as follows:
```
$ objdump -d t-openclose-4.8.4
  ...
Disassembly of section .got:

0000000000600fb0 <_GLOBAL_OFFSET_TABLE_>:
  600fb0:       c0 0d 60 00 00 00 00    rorb   $0x0,0x60(%rip)        # 601017 <__TMC_END__+0x7>
        ...
  600fc7:       00 f6                   add    %dh,%dh
  600fc9:       04 40                   add    $0x40,%al
  600fcb:       00 00                   add    %al,(%rax)
  600fcd:       00 00                   add    %al,(%rax)
  600fcf:       00 06                   add    %al,(%rsi)
  600fd1:       05 40 00 00 00          add    $0x40,%eax
  600fd6:       00 00                   add    %al,(%rax)
  600fd8:       16                      (bad)
  600fd9:       05 40 00 00 00          add    $0x40,%eax
  600fde:       00 00                   add    %al,(%rax)
  600fe0:       26                      es
  600fe1:       05 40 00 00 00          add    $0x40,%eax
  600fe6:       00 00                   add    %al,(%rax)
  600fe8:       36                      ss
  600fe9:       05 40 00 00 00          add    $0x40,%eax
  600fee:       00 00                   add    %al,(%rax)
  600ff0:       46 05 40 00 00 00       rex.RX add $0x40,%eax
        ..
  ...
```

**Comment by honggyukim** [comment] 2017-08-25 06:24
Even if I add `-pie -fPIE` option to gcc-4.8.4, uftrace output is not properly shown:
```
$ gcc -o t-openclose-4.8.4 -fno-inline -fno-builtin -fno-omit-frame-pointer  -finstrument-functions -Os  s-openclose.c   -Wl,-z,now -Wl,-z,relro

$ uftrace t-openclose-4.8.4
# DURATION    TID     FUNCTION
            [31550] | main() {
   7.203 us [31550] |   <400530>();
  13.446 us [31550] | } /* main */

$ gcc -o t-openclose-4.8.4-pie -pie -fPIE -fno-inline -fno-builtin -fno-omit-frame-pointer  -finstrument-functions -Os  s-openclose.c   -Wl,-z,now -Wl,-z,relro

$ uftrace t-openclose-4.8.4-pie
# DURATION    TID     FUNCTION
            [31449] | main() {
   7.093 us [31449] |   open();
  13.226 us [31449] | } /* main */
```
Please ignore the function inside `main`, it's a gcc bug.

**Comment by honggyukim** [comment] 2017-08-25 06:46
I think you better test it with `clang` that doesn't have `-finstrument-functions` bug.
```
$ clang -o t-openclose-clang -finstrument-functions -Os  s-openclose.c -Wl,-z,now -Wl,-z,relro
$ uftrace t-openclose-clang
# DURATION    TID     FUNCTION
   5.678 us [ 3441] | main();

$ clang -o t-openclose-clang-pie -pie -fPIE -finstrument-functions -Os  s-openclose.c -Wl,-z,now -Wl,-z,relro
$ uftrace t-openclose-clang-pie
# DURATION    TID     FUNCTION
  10.730 us [ 3475] | main();
```

**Comment by namhyung** [comment] 2017-08-26 13:35
Thanks for the info.  I pushed a possible solution to [check/pie-fix](https://github.com/namhyung/uftrace/compare/check/pie-fix).  Could you please test?

**Comment by honggyukim** [comment] 2017-08-27 06:15
@namhyung Hm.. there's some more problems.
```
$ gcc -o t-openclose -fno-inline -fno-builtin -fno-omit-frame-pointer  -finstrument-functions -O0  s-openclose.c   -Wl,-z,now -Wl,-z,relro
$ uftrace -vv t-openclose
symbol: check trace functions in t-openclose
uftrace: creating 1 thread(s) for recording
uftrace: using libmcount.so library for tracing
uftrace: start writer thread 0
mcount: initializing mcount library
symbol: load dynamic symbols for bind-now
symbol: loaded 6 symbols from .plt.got section
mcount: opening executable image: /home/honggyu/work/uftrace/git/uftrace/tests/t-openclose
uftrace: setup bind-now PLT trampoline at 0x7f12055db000
uftrace: real address to jump: 0x4004d0
mcount: mcount setup done
uftrace: MSG SESSION: 5325: /home/honggyu/work/uftrace/git/uftrace/tests/t-openclose (da61ef04cc3ebc70)
mcount: preparing shmem buffers
uftrace: MSG START: /uftrace-da61ef04cc3ebc70-5325-000
uftrace: MSG TASK_START : 5325/5325
```
It just stucks this point and does not finish the program. Even if I compile it with clang, it shows the same result.

The below commit makes the program stuck.
d7b1c90 (HEAD) arch/x86: Implement mcount_arch_undo_bindnow()

**Comment by honggyukim** [comment] 2017-08-27 06:17
We may have to look into ld linker source code for this case. I don't know if it's useful or not but I've found something related to `-z relro`, so put the link here for later reference.
https://github.com/bminor/binutils-gdb/commit/8c37241be3b1baf394090269b4b67babceb83d61

**Comment by namhyung** [comment] 2017-08-28 02:42
Now sure what's the problem.  But I cannot reproduce even with clang..


> uftrace: real address to jump: 0x4004d0

It'd be nice if you could show me the disassembly of 0x4004d0 and whether dynamic table (readelf -d) has `JMPREL` tag.  In the above example, the jump addresses should be 0x4004e0 instead.

**Comment by honggyukim** [comment] 2017-08-28 02:56
Here is the disassemble output:
```
Disassembly of section .plt:

00000000004004d0 <.plt>:
  4004d0:       ff 35 ea 0a 20 00       pushq  0x200aea(%rip)        # 600fc0 <_GLOBAL_OFFSET_TABLE_+0x8>
  4004d6:       ff 25 ec 0a 20 00       jmpq   *0x200aec(%rip)        # 600fc8 <_GLOBAL_OFFSET_TABLE_+0x10>
  4004dc:       0f 1f 40 00             nopl   0x0(%rax)

Disassembly of section .plt.got:

00000000004004e0 <.plt.got>:
  4004e0:       ff 25 ea 0a 20 00       jmpq   *0x200aea(%rip)        # 600fd0 <_GLOBAL_OFFSET_TABLE_+0x18>
  4004e6:       66 90                   xchg   %ax,%ax
  4004e8:       ff 25 ea 0a 20 00       jmpq   *0x200aea(%rip)        # 600fd8 <_GLOBAL_OFFSET_TABLE_+0x20>
  4004ee:       66 90                   xchg   %ax,%ax
  4004f0:       ff 25 ea 0a 20 00       jmpq   *0x200aea(%rip)        # 600fe0 <_GLOBAL_OFFSET_TABLE_+0x28>
  4004f6:       66 90                   xchg   %ax,%ax
  4004f8:       ff 25 ea 0a 20 00       jmpq   *0x200aea(%rip)        # 600fe8 <_GLOBAL_OFFSET_TABLE_+0x30>
  4004fe:       66 90                   xchg   %ax,%ax
  400500:       ff 25 ea 0a 20 00       jmpq   *0x200aea(%rip)        # 600ff0 <_GLOBAL_OFFSET_TABLE_+0x38>
  400506:       66 90                   xchg   %ax,%ax
  400508:       ff 25 ea 0a 20 00       jmpq   *0x200aea(%rip)        # 600ff8 <_GLOBAL_OFFSET_TABLE_+0x40>
  40050e:       66 90                   xchg   %ax,%ax
```
Dynamic table:
```
$ readelf -d t-openclose

Dynamic section at offset 0xdf8 contains 23 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000c (INIT)               0x4004b0
 0x000000000000000d (FINI)               0x4006d4
 0x0000000000000019 (INIT_ARRAY)         0x600de0
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x600de8
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x400298
 0x0000000000000005 (STRTAB)             0x400378
 0x0000000000000006 (SYMTAB)             0x4002d0
 0x000000000000000a (STRSZ)              116 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000003 (PLTGOT)             0x600fb8
 0x0000000000000007 (RELA)               0x400420
 0x0000000000000008 (RELASZ)             144 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x0000000000000018 (BIND_NOW)
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x000000006ffffffe (VERNEED)            0x400400
 0x000000006fffffff (VERNEEDNUM)         1
 0x000000006ffffff0 (VERSYM)             0x4003ec
 0x0000000000000000 (NULL)               0x0
```

**Comment by honggyukim** [comment] 2017-08-28 03:01
@namhyung You can download the binary as follows:
```
$ wget --no-check-certificate honggyu.zetacode.com/t-openclose
$ chmod +x t-openclose
```

**Comment by namhyung** [comment] 2017-08-28 03:03
@honggyukim Thanks! I'll take a look.

**Comment by honggyukim** [comment] 2017-08-28 03:04
> Now sure what's the problem. But I cannot reproduce even with clang..

FYI, we don't see any difference even with clang because clang uses the same system `ld` linker by default. It seems that bind-now and pie are purely linker issues.

> @honggyukim Thanks! I'll take a look.

Thanks a lot for your effort!

**Comment by namhyung** [comment] 2017-08-28 04:57
Hmm.. this binary's PLT structure is same as mine.  But it had to skip `__gmon_start__` for some reason.  Please try the patch below (also attached: [bind-now-fix.patch](https://github.com/namhyung/uftrace/files/1255144/bind-now-fix.patch.txt))

```
diff --git a/arch/x86_64/mcount-support.c b/arch/x86_64/mcount-support.c
index 33bf780..d09552e 100644
--- a/arch/x86_64/mcount-support.c
+++ b/arch/x86_64/mcount-support.c
@@ -156,6 +156,7 @@ int mcount_arch_undo_bindnow(Elf *elf, struct symtabs *symtabs,
                "mcount", "__fentry__",
                "__cyg_profile_func_enter", "__cyg_profile_func_exit",
                "__cxa_finalize",  /* XXX: it caused segfault */
+               "__gmon_start__",
        };

        plthook_setup(symtabs);
```

And could you send me a binary compiled with GCC 4.8.4 as well?

**Comment by honggyukim** [comment] 2017-08-28 05:08
Please download them as follows:
```
$ wget --no-check-certificate honggyu.zetacode.com/t-openclose-4.8.5
$ wget --no-check-certificate honggyu.zetacode.com/t-openclose-5.4.0
$ wget --no-check-certificate honggyu.zetacode.com/t-openclose-6.3.0
```
They are compiled with `-finstrument-functions -O0 -Wl,-z,now -Wl,-z,relro`.

**Comment by honggyukim** [comment] 2017-08-28 05:09
The thing is that I didn't know that but my server has upgraded gcc from 4.8.4 to 5.4.0 so I gave you the same binary as yours.

**Comment by namhyung** [comment] 2017-08-28 05:22
The binary compiled with GCC 4.8 also has same PLT structure and it worked fine with the above patch..  Is it an issue with 4.8.4?

**Comment by namhyung** [comment] 2017-08-28 05:23
Or maybe due to your linker version..

**Comment by honggyukim** [comment] 2017-08-28 05:47
Here is the result in my system.
```
build command: gcc -o t-openclose -fno-inline -fno-builtin -fno-omit-frame-pointer  -finstrument-functions -O0  s-openclose.c   -Wl,-z,now -Wl,-z,relro
test command: ../uftrace --no-pager -L.. t-openclose
=========== original ===========
# DURATION    TID     FUNCTION
            [16031] | main() {
   3.887 us [16031] |   open();
   1.783 us [16031] |   close();
   7.653 us [16031] | } /* main */

===========  result  ===========
main() {
   open();
   close();
 } /* main */
=========== expected ===========
main() {
   open();
   close();
 } /* main */
build command: gcc -o t-openclose -fno-inline -fno-builtin -fno-omit-frame-pointer  -finstrument-functions -O1  s-openclose.c   -Wl,-z,now -Wl,-z,relro
test command: ../uftrace --no-pager -L.. t-openclose
build command: gcc -o t-openclose -fno-inline -fno-builtin -fno-omit-frame-pointer  -finstrument-functions -O2  s-openclose.c   -Wl,-z,now -Wl,-z,relro
test command: ../uftrace --no-pager -L.. t-openclose
build command: gcc -o t-openclose -fno-inline -fno-builtin -fno-omit-frame-pointer  -finstrument-functions -O3  s-openclose.c   -Wl,-z,now -Wl,-z,relro
test command: ../uftrace --no-pager -L.. t-openclose
build command: gcc -o t-openclose -fno-inline -fno-builtin -fno-omit-frame-pointer  -finstrument-functions -Os  s-openclose.c   -Wl,-z,now -Wl,-z,relro
test command: ../uftrace --no-pager -L.. t-openclose
161 pltbind_now         : OK OK OK OK OK OK SG SG SG SG
```
From -O1 to -Os got segfaults while running. The versions are
```
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.26.1
Copyright (C) 2015 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

**Comment by honggyukim** [comment] 2017-08-28 05:50
Here is more info for gcc-6.3.0 in another machine.
```
$ gcc --version
gcc (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.28
Copyright (C) 2017 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

**Comment by namhyung** [comment] 2017-08-28 05:54
Please give me a link to a binary causes segfault, thanks!

**Comment by honggyukim** [comment] 2017-08-28 05:57
Ah.. sorry for making you busy but please see the below binaries. I made them using gcc-4.8.4 not 4.8.5.
```
$ wget --no-check-certificate honggyu.zetacode.com/t-openclose-4.8.4-O0
$ wget --no-check-certificate honggyu.zetacode.com/t-openclose-4.8.4-O2
```
Here is the uftrace results:
```
$ uftrace t-openclose-4.8.4-O0
# DURATION    TID     FUNCTION
  13.643 us [ 8520] | main();

$ uftrace t-openclose-4.8.4-O2
# DURATION    TID     FUNCTION
            [ 8533] | main() {
   5.960 us [ 8533] |   <400530>();
  10.960 us [ 8533] | } /* main */
```
It seems that linker is much older version. Here's the version info:
```
$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.24
Copyright 2013 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

**Comment by honggyukim** [comment] 2017-08-28 06:03
> Please give me a link to a binary causes segfault, thanks!

Ah.. please ignore this issue. It's because of gcc bug that I said above. I tested it again with clang and it works fine.

**Comment by namhyung** [comment] 2017-08-28 06:15
OK, I just pushed the new fix to [check/pie-fix](https://github.com/namhyung/uftrace/compare/check/pie-fix), please test again!

**Comment by honggyukim** [comment] 2017-08-28 06:19
Hm.. it doesn't work.
```
$ gcc -o t-openclose -fno-inline -fno-builtin -fno-omit-frame-pointer  -pg -O0  s-openclose.c   -Wl,-z,now -Wl,-z,relro

$ uftrace t-openclose
mcount: /home/honggyu/src/uftrace/git/uftrace/libmcount/plthook.c:725:plthook_exit
 ERROR: <2> invalid dynsym idx: 65535
# DURATION    TID     FUNCTION
   1.080 us [12935] | __monstartup();
   0.363 us [12935] | __cxa_atexit();
```

**Comment by namhyung** [comment] 2017-08-28 06:41
Sorry, please give me a link for -pg build binary too.

**Comment by honggyukim** [comment] 2017-08-28 06:52
Here's the binary above that is compiled with `-pg`.
```
$ wget --no-check-certificate honggyu.zetacode.com/t-openclose-4.8.4-pg-O0
$ wget --no-check-certificate honggyu.zetacode.com/t-openclose-4.8.4-pg-O2
```

**Comment by namhyung** [comment] 2017-08-28 07:04
OK, it was due to missing check for skip symbols.  New code was pushed to the [check/pie-fix](https://github.com/namhyung/uftrace/compare/check/pie-fix).

```
$ uftrace t-openclose-4.8.4-pg-O2
# DURATION    TID     FUNCTION
   0.613 us [ 8583] | __monstartup();
   0.216 us [ 8583] | __cxa_atexit();
            [ 8583] | main() {
   5.816 us [ 8583] |   open();
   4.000 us [ 8583] |   close();
  11.052 us [ 8583] | } /* main */
```

**Comment by honggyukim** [comment] 2017-08-28 07:10
Thanks! It works fine now for gcc-4.8.4, gcc-4.8.5, gcc-5.4.0, and gcc-6.3.0 although the tests are failed in `-finstrument-functions` due to the gcc internal bug.

**Comment by namhyung** [comment] 2017-08-28 07:13
Good! many thanks for testing all the combination.

@ssove Could you please confirm that it fixes your problem as well?

**Comment by honggyukim** [comment] 2017-08-28 07:17
@namhyung Why don't we change the testcase to avoid the gcc bug before asking the test? Anyway, the test result will be failed and it's difficult to distinguish whether it is the problem of gcc or uftrace.

**Comment by honggyukim** [comment] 2017-08-28 07:24
What about this? :)
```
diff --git a/tests/s-openclose.c b/tests/s-openclose.c
index 50dc77c..2c32bae 100644
--- a/tests/s-openclose.c
+++ b/tests/s-openclose.c
@@ -1,9 +1,7 @@
 #include <stdio.h>
-#include <unistd.h>
-#include <fcntl.h>

 int main(void)
 {
-       close(open("/dev/null", O_RDONLY));
+       fclose(fopen("/dev/null", "r"));
        return 0;
 }
diff --git a/tests/t161_pltbind_now.py b/tests/t161_pltbind_now.py
index 065ef1a..2325603 100644
--- a/tests/t161_pltbind_now.py
+++ b/tests/t161_pltbind_now.py
@@ -7,8 +7,8 @@ class TestCase(TestBase):
         TestBase.__init__(self, 'openclose', """
 # DURATION    TID     FUNCTION
             [15973] | main() {
-   5.903 us [15973] |   open();
-   4.374 us [15973] |   close();
+   5.903 us [15973] |   fopen();
+   4.374 us [15973] |   fclose();
   15.262 us [15973] | } /* main */
 """)

```
It passes all the tests.

**Comment by namhyung** [comment] 2017-08-28 07:56
Not sure why it makes the difference.  Anyway the openclose test is used in other places too.

**Comment by honggyukim** [comment] 2017-08-28 08:06
It's a bug for some specific cases and the important thing is that it is fixed in gcc-6.xx  anyway. So I think we better just detour this case. Most of tests that use `s-openclose.c` are kernel tests so skipped in usual but have the same problem. For example,
```
$ sudo ./runtest.py -v 79
    ...
build command: gcc -o t-openclose -fno-inline -fno-builtin -fno-omit-frame-pointer  -finstrument-functions -O3  s-openclose.c
test command: ../uftrace --no-pager -L.. replay -k -D3 -d xxx
=========== original ===========
# DURATION    TID     FUNCTION
            [91031] | main() {
            [91031] |   open() {
  30.477 us [91031] |     open();
  35.507 us [91031] |   } /* open */
            [91031] |   close() {
   3.947 us [91031] |     sys_close();
  10.257 us [91031] |     exit_to_usermode_loop();
  16.193 us [91031] |   } /* close */
  52.991 us [91031] | } /* main */

===========  result  ===========
main() {
   open() {
     open();
   } /* open */
   close() {
     sys_close();
     exit_to_usermode_loop();
   } /* close */
 } /* main */
=========== expected ===========
main() {
   open() {
     sys_open();
   } /* open */
   close() {
     sys_close();
     exit_to_usermode_loop();
   } /* close */
 } /* main */
    ...
079 replay_kernel_D     : OK OK OK OK OK OK NG NG NG NG
```
We can change other tests which use s-openclose.c source file.

**Comment by honggyukim** [comment] 2017-08-28 09:50
I've made a PR to avoid the bug in #138. Please take a look at it.

**Comment by honggyukim** [comment] 2017-08-28 10:24
One more thing is that newly added testcase cannot be compile in my Ubuntu system.
```
162 pltbind_now_pie     : BI BI BI BI BI BI BI BI BI BI
```
```
$ gcc -o t-openclose -fno-inline -fno-builtin -fno-omit-frame-pointer  -pg -O0 -fpie  s-openclose.c   -Wl,-pie,-z,now,-z,relro
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/crtbegin.o: relocation R_X86_64_32 against `__TMC_END__' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/crtbegin.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
```

**Comment by honggyukim** [comment] 2017-08-28 10:38
One more minor warning issue,
```
$ make
    ...
  CC       arch/x86_64/symbol.o
/home/honggyu/src/uftrace/git/uftrace/arch/x86_64/symbol.c: In function ‘arch_load_dynsymtab_bindnow’:
/home/honggyu/src/uftrace/git/uftrace/arch/x86_64/symbol.c:106:3: warning: ‘nr_rels’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   for (idx = 0; idx < nr_rels; idx++) {
   ^
  LINK     arch/x86_64/uftrace.o
```

**Comment by namhyung** [comment] 2017-08-28 11:53
Thanks, will fix.  It seems old gcc has some bugs related to PIE..

**Comment by namhyung** [comment] 2017-09-01 14:52
@ssove I'm going to close this issue with the fix as @honggyukim tested it.  If you still have any trouble, please reopen this or file a new one, thanks!

**Closed** 2017-09-01 14:54 UTC
Labels: bug
